### ISSUE TITLE
Tracking dependencies?

### ISSUE THREAD

**Issue by danse** [christophergandrud/eu_ms_statistical_agency_tenure#1]
Hey hello, i wanted to check out your exploration here. I am trying by running:

    $ R -f directors_exploration.R

I adjusted the base directory, but i still have problems because i am missing some libraries. Now, i could install the libraries one by one, but hopefully there is a way to track dependencies per project with some R configuration file, or you keep these libraries installed system-wide? I hope this is not too much a stupid question

**Comment by christophergandrud** [comment]
The packages are installed locally. 

Note: this is a **super early** stage project.

**Comment by danse** [comment]
> Note: this is a super early stage project.

Of course, i don't have any expectation. I am just asking because i am curious about best practices in R dev
